site_name: Allxon
repo_url: https://github.com/wayneliu0512/academy_mkdocs
repo_name: wayneliu0512/academy_mkdocs
nav:
  - Home: index.md
  - Agile Development: 
    - Agile: agile_project_management/agile_development.md
    - Jira: agile_project_management/jira_project_management.md
    - Kanban: agile_project_management/kanban.md
    - Scrum: agile_project_management/scrum.md
    - Software Development: agile_project_management/software_development.md
  - C++:
    - Variables and Types: c++/variables_types.md
    - Compound Type: c++/compound_type.md
    - Class: c++/class.md
    - Copy Control: c++/copy_control.md
    - Object Oriented Programming: c++/object_oriented_programming.md
    - Smart Pointer: c++/smart_pointer.md
    - Template: c++/template.md
    - Exception: c++/exception.md
    - Effective C++: c++/effective_cpp.md
    - C++ 11 Feature: c++/cpp11_feature.md
  - Git:
    - Introduction: git/getting_started.md
    - Basic: git/clone_recording_changes.md
    - Branching: git/branching_nutshell.md
    - Branching and Merging: git/branching_merging.md
    - Branch Management: git/branch_mang_remote.md
    - Remote Branches: git/remote.md
    - Rebasing: git/rebasing.md
  - Object Oriented Programming:
    - SOLID: ood/solid.md
    - Package Coupling: ood/coupling_packages.md
    - Package Cohesion: ood/package_cohesion.md
  - Others:
    - Design Pattern:
      - Strategy: design_pattern/strategy.md
      - Command: design_pattern/command.md
      - Factory: design_pattern/factory.md
      - Decorator: design_pattern/decorator.md
      - Observer: design_pattern/observer.md
      - Singleton: design_pattern/singleton.md
    - Qt:
      - Model View: qt/model_view.md
      - Threading and Event: qt/qt_threading_event.md
    - ROS: ros/ros.md
    - Concurrency: concurrency/concurrency.md
    - Google Mock: google_mock.md
    

theme:
  name: material
  favicon: assets/images/favicon.ico
  logo: images/windows_icon.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: allxon
      accent: light blue
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: allxon
      accent: light blue
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.top
markdown_extensions:
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.superfences
extra_css:
  - stylesheets/extra.css